plugins {
    id 'java'
    id 'org.springframework.boot' version '3.3.5'
    id 'io.spring.dependency-management' version '1.1.6'
}

group = 'com.aleksandr_kobelskiy'
version = '1.0.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.session:spring-session-core'
    implementation 'org.springframework.boot:spring-boot-starter-data-r2dbc'
    implementation 'org.springframework.security:spring-security-config'

    implementation 'software.amazon.awssdk:netty-nio-client:2.29.21' // Убедитесь, что версия актуальная

//  Реактивный драйвер работы с MySQL
    implementation "io.asyncer:r2dbc-mysql:$r2dbcMysqlVersion"

//  Стандартный JDBC драйвер MySQL
    implementation "com.mysql:mysql-connector-j:$mysqlConnectorJVersion"

//    implementation 'org.flywaydb:flyway-core'
    implementation "org.flywaydb:flyway-core:$flywayCoreVersion"
    implementation "org.flywaydb:flyway-mysql:$flywayMysqlVersion"

//  Убирает Warnings при сборке
    implementation "com.github.spotbugs:spotbugs-annotations:$spotbugsAnnotationsVersion"

//  Для преобразования моделей в DTO
    implementation "org.mapstruct:mapstruct:$mapStructVersion"

//  Работа с JWT
    implementation "io.jsonwebtoken:jjwt-api:$jsonWebTokenVersion"

//  Отключение 100500 Warnings
    implementation "javax.xml.bind:jaxb-api:$jaxbApiVersion"

//  Чтобы не писать самому Getters and Setters
    annotationProcessor 'org.projectlombok:lombok'

    annotationProcessor "org.mapstruct:mapstruct-processor:$mapStructVersion"

    implementation 'org.springframework.boot:spring-boot-configuration-processor'

//  Amazon AWS S3
    implementation "software.amazon.awssdk:s3:$awsSdkVersion"

//  Reactor Core
    implementation "io.projectreactor:reactor-core:$reactorCoreVersion"

    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.11.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.11.5'
    compileOnly 'org.projectlombok:lombok'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.boot:spring-boot-testcontainers'
    testImplementation "io.projectreactor:reactor-test:$reactorTestVersion"
    testImplementation "org.testcontainers:mysql:$testcontainersMysqlVersion"
    testImplementation 'org.testcontainers:junit-jupiter'
    testImplementation 'org.testcontainers:r2dbc'
    testImplementation 'org.springframework.security:spring-security-test'
    testImplementation "org.testcontainers:localstack:$testcontainersLocalstackVersion"
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}
