server.port=8787

spring.application.name=week12practice

#spring.r2dbc.url=r2dbc:mysql://localhost:3306/week12practice
spring.r2dbc.url=r2dbc:mysql://10.13.2.203:3306/week12practice
spring.r2dbc.username=root
spring.r2dbc.password=password

#spring.flyway.url=jdbc:mysql://localhost:3306/week12practice
spring.flyway.url=jdbc:mysql://10.13.2.203:3306/week12practice
spring.flyway.user=root
spring.flyway.password=password
spring.flyway.locations=classpath:db/migration

#spring.datasource.url=jdbc:mysql://localhost:3306/week12practice
#spring.datasource.username=root
#spring.datasource.password=password
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Включаем автоматическую миграцию Flyway при запуске приложения
#spring.flyway.enabled=true

# Указываем путь к миграционным файлам (по умолчанию: classpath:db/migration)
#spring.flyway.locations=classpath:db/migration

# Реактивное подключение
#spring.r2dbc.url=r2dbc:pool:mysql://localhost:3306/week12practice
#spring.r2dbc.url=r2dbc:mysql://localhost:3306/week12practice
#spring.r2dbc.username=root
#spring.r2dbc.password=password

# Опциональные настройки пула соединений
#spring.r2dbc.pool.initial-size=5
#spring.r2dbc.pool.max-size=20

# Создаём таблицы в БД на основе наших классов
#spring.jpa.generate-ddl=true

#jwt.token.secret=week12practice
#jwt.token.expired=3600000

jwt.password.encoder.secret=FZK2DZ82odqS13e8aENggaMbb_fAkl-nJL4AEVBX43g
jwt.password.encoder.iteration=64
jwt.password.encoder.keylength=256
jwt.secret=b5f59337a612a2a7dc07328f3e7d1a04722967c7f06df20a499a7d3f91ff2a7e
jwt.expiration=3600
jwt.issuer=akobelskiy

aws.s3.accessKey=YCAJEoVUVbNAJxUT0LBAzsPA7
aws.s3.secret=YCOdSPOlZYp_EcqFVaCxqoGGePn953ZFOxPMzC9T
aws.s3.bucketName=javateam1
#aws.s3.regionName=ru-central1-a
aws.s3.personalFolderName=akobelskiy

