server.port=8787

spring.application.name=week12practice

spring.r2dbc.url=r2dbc:mysql://localhost:3306/week12practice
#spring.r2dbc.url=r2dbc:mysql://10.13.2.203:3306/week12practice
spring.r2dbc.username=root
spring.r2dbc.password=password

spring.flyway.url=jdbc:mysql://localhost:3306/week12practice
#spring.flyway.url=jdbc:mysql://10.13.2.203:3306/week12practice
spring.flyway.user=root
spring.flyway.password=password
spring.flyway.locations=classpath:db/migration

jwt.password.encoder.secret=FZK2DZ82odqS13e8aENggaMbb_fAkl-nJL4AEVBX43g
jwt.password.encoder.iteration=64
jwt.password.encoder.keylength=256
jwt.secret=b5f59337a612a2a7dc07328f3e7d1a04722967c7f06df20a499a7d3f91ff2a7e
jwt.expiration=3600
jwt.issuer=akobelskiy

# AWS S3 конфигурация
aws.s3.endpointOverride=https://storage.yandexcloud.net
aws.s3.accessKey=YCAJEoVUVbNAJxUT0LBAzsPA7
aws.s3.secretKey=YCOdSPOlZYp_EcqFVaCxqoGGePn953ZFOxPMzC9T
aws.s3.bucketName=javateam1
aws.s3.regionName=ru-central1-a
aws.s3.personalFolderName=akobelskiy

